name: BATS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  bats:
    runs-on: ubuntu-latest
    container: <image with Git v2.18+ installed>
    strategy:
      matrix:
        bash: ["bash:5.0", "bash:5.1", "bash:5.2"]
    container: 
      image: ${{ matrix.bash }}
    steps:
      - name: Install packages
        run: apk add diffutils bats
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: true        
      - name: Git Submodule Update
        run: |
          git pull --recurse-submodules
          git submodule update --remote --recursive
      - name: Run bash tests
        run: cd test && bats test.bats

