name: BATS Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  bats:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bash: ["bash:5.0", "bash:5.1", "bash:5.2"]
    container: 
      image: ${{ matrix.bash }}
    steps:
      - name: Install packages
        run: apk add diffutils bats git
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Run bash tests
        run: cd test && bats test.bats

